### ISSUE TITLE
Failed to activate the vim-mode package

### ISSUE THREAD

**Issue by zba** [robballou/atom-copy-on-select#2]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0-7c2b9fa
**System**: linux 3.13.0-46-generic
**Thrown From**: [atom-copy-on-select](https://github.com/robballou/atom-copy-on-select) package, v1.2.0

### Stack Trace

Failed to activate the vim-mode package

```
At Cannot read property 'getSelectedText' of undefined

TypeError: Cannot read property 'getSelectedText' of undefined
  at Object.atomCopyOnSelect.selectionChanged (/home/user/.atom/packages/atom-copy-on-select/lib/atom-copy-on-select.js:61:58)
  at /home/user/.atom/packages/atom-copy-on-select/lib/atom-copy-on-select.js:44:24
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.selectionRangeChanged (/usr/share/atom/resources/app/src/text-editor.js:2215:27)
  at Selection.module.exports.Selection.screenRangeChanged (/usr/share/atom/resources/app/src/selection.js:883:26)
  at /usr/share/atom/resources/app/src/selection.js:43:24
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.notifyObservers (/usr/share/atom/resources/app/src/marker.js:299:22)
  at /usr/share/atom/resources/app/src/marker.js:56:24
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.update (/usr/share/atom/resources/app/node_modules/text-buffer/lib/marker.js:569:22)
  at Marker.module.exports.Marker.setHeadPosition (/usr/share/atom/resources/app/node_modules/text-buffer/lib/marker.js:223:19)
  at Marker.module.exports.Marker.setHeadBufferPosition (/usr/share/atom/resources/app/src/marker.js:210:32)
  at Marker.module.exports.Marker.setHeadScreenPosition (/usr/share/atom/resources/app/src/marker.js:220:19)
  at /usr/share/atom/resources/app/src/cursor.js:114:31
  at Cursor.module.exports.Cursor.changePosition (/usr/share/atom/resources/app/src/cursor.js:684:7)
  at Cursor.module.exports.Cursor.setScreenPosition (/usr/share/atom/resources/app/src/cursor.js:112:19)
  at Cursor.module.exports.Cursor.moveLeft (/usr/share/atom/resources/app/src/cursor.js:309:21)
  at VimState.module.exports.VimState.deactivateInsertMode (/home/user/.atom/packages/vim-mode/lib/vim-state.coffee:407:14)
  at VimState.module.exports.VimState.activateCommandMode (/home/user/.atom/packages/vim-mode/lib/vim-state.coffee:370:6)
  at new VimState (/home/user/.atom/packages/vim-mode/lib/vim-state.coffee:43:8)
  at /home/user/.atom/packages/vim-mode/lib/vim-mode.coffee:22:24
  at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app/src/workspace.js:282:9)
  at Object.module.exports.activate (/home/user/.atom/packages/vim-mode/lib/vim-mode.coffee:16:37)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:240:19)
  at /usr/share/atom/resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:461:21)
  at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:63:47)
  at /usr/share/atom/resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:150:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jsformat",
      "git-plus",
      "git-blame",
      "project-manager"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v0.6.2
atom-color-highlight, v3.0.8
atom-copy-on-select, v1.2.0
autocomplete-plus, v2.7.1
color-picker, v1.5.0
file-icons, v1.5.2
file-type-icons, v0.5.4
fonts, v0.4.0
git-diff-details, v0.8.0
git-log, v0.3.0
git-tab-status, v1.6.0
highlight-line, v0.10.1
highlight-selected, v0.9.1
javascript-snippets, v1.0.0
language-css-plus, v0.3.0
language-ejs, v0.1.0
language-javascript-semantic, v0.1.0
language-stylus, v0.1.0
linter, v0.12.0
linter-csslint, v0.0.11
linter-eslint, v0.5.0
linter-htmlhint, v0.0.12
linter-jscs, v1.9.0
linter-jshint, v0.1.0
minimap, v4.7.2
minimap-color-highlight, v4.1.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.0
minimap-selection, v4.2.0
save-session, v0.12.5
tab-history, v0.4.0
toolbar, v0.0.12
toolbar-main, v0.0.5
tree-view-breadcrumb, v0.4.1
vim-mode, v0.42.0

# Dev
No dev packages
```

**Comment by robballou** [comment]
Thanks for reporting this issue! I've encountered similar but always fail to get around to fixing it :grimacing:

I have committed a change to checkout and see if that helps. If so let me know and I'll publish a new version.

**Comment by zba** [comment]
Thanks, i can't repeat problem anymore :( (even without patch) it seems the problem is related to broken copy/paste in atom itself (it appears in 0.18x versions) I'll let you know if anything will report again about the package

**Comment by robballou** [comment]
Sounds good! I published a new version with this change and another small change but I'll consider it closed. Thanks for submitting.
