### ISSUE TITLE
Failed to load the atom-copy-on-select package

### ISSUE THREAD

**Issue by jesusmah** [robballou/atom-copy-on-select#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [atom-copy-on-select](https://github.com/robballou/atom-copy-on-select) package 1.5.0

### Stack Trace

Failed to load the atom-copy-on-select package

```
At Cannot find module 'jquery'

Error: Cannot find module 'jquery'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-copy-on-select/lib/atom-copy-on-select.js:10:9)
    at /packages/atom-copy-on-select/lib/atom-copy-on-select.js:122:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:143:22)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:16)
    at config.transact (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:531:20)
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:342:22)
    at PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:529:23)
    at loadStatePromise.loadState.then (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:818:27)
```

### Commands

```
     -0:05.5.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-copy-on-select 1.5.0 
jQuery 1.2.5 
native-ui 0.25.2 
seti-ui 1.9.0 
single-click-open 0.2.2 
```

**Comment by jesusmah** [comment]
To sort our this error:

`cd ~/.atom/packages/atom-copy-on-select`
`npm install jquery`

shouldnt jquery be part of the project if it is required to run?

**Comment by robballou** [comment]
Hi there,

Sorry you're having issues. jQuery is listed in `package.json` so I'm not sure what the issue was: https://github.com/robballou/atom-copy-on-select/blob/master/package.json

I just installed the package with a clean installation and everything worked. There may have been an upgrade path issue as the jQuery version changed, but I haven't tested that.
